# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HandySshd < Formula
  desc "Portable SSH server"
  homepage "https://github.com/nwtgck/handy-sshd"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.2.0/handy-sshd-0.2.0-darwin-amd64.tar.gz"
      sha256 "3b290f67372edeaec43615bec3b301faaa06b3c2b595fd4e5921c12da939428f"

      def install
        bin.install "handy-sshd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.2.0/handy-sshd-0.2.0-linux-amd64.tar.gz"
      sha256 "59b63cb20a492b01f0ebd4fda2f2e1f6ef9d633df6471c70ec0780e0a53efefb"

      def install
        bin.install "handy-sshd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.2.0/handy-sshd-0.2.0-linux-armv6.tar.gz"
      sha256 "8dccdd85074c815b2e0708b79fafabd1108a396a009bcc1c04098bd52d59d476"

      def install
        bin.install "handy-sshd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.2.0/handy-sshd-0.2.0-linux-arm64.tar.gz"
      sha256 "bda7dfa1da8fcbe643cee857f8a3030cdbd686d09bdf8bba248322f086a5832a"

      def install
        bin.install "handy-sshd"
      end
    end
  end
end
