# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HandySshd < Formula
  desc "Portable SSH server"
  homepage "https://github.com/nwtgck/handy-sshd"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.4.0/handy-sshd-0.4.0-darwin-arm64.tar.gz"
      sha256 "02694251a38a8e43943ab49206ba7dd82044c6ff1cfbb75f0cdc64995deb5d59"

      def install
        bin.install "handy-sshd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.4.0/handy-sshd-0.4.0-darwin-amd64.tar.gz"
      sha256 "2c18bb5dd82a7c03ab79ed22d5dedf8f53c0c10a6cc0d7c4c9bc18683a4783b6"

      def install
        bin.install "handy-sshd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.4.0/handy-sshd-0.4.0-linux-armv6.tar.gz"
      sha256 "7fb332816babe54ad557a44dd61357cc4ab1f07f694e4f6731c73869dcc41a3b"

      def install
        bin.install "handy-sshd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.4.0/handy-sshd-0.4.0-linux-arm64.tar.gz"
      sha256 "f34976e8445696a17a43b25fd74f215ba06a718d9045b57af2aaebb4c44ef1a6"

      def install
        bin.install "handy-sshd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/handy-sshd/releases/download/v0.4.0/handy-sshd-0.4.0-linux-amd64.tar.gz"
      sha256 "a630b5e307466681282cdb8cf5c68e28f25a821ca613cd83e440d9afa27897c5"

      def install
        bin.install "handy-sshd"
      end
    end
  end
end
